### ISSUE TITLE
flexible catheter

### ISSUE THREAD

**Issue by Zimmo95** [WPI-AIM/ambf#120]
Hi Adnan,
I would like to create a flexible catheter for vascular inspections.
I started creating a long and thin cylinder on blender and saving the stl and .yaml file using the blender addon. 
Then, I added "soft bodies" in the yaml file but the cylinder (in ambf) still remained rigid and also penetrated through the floor.
Can you explain me how to create a flexible cylinder able to sag?
 
Thanks for your availability,

Enrico

**Comment by adnanmunawar** [comment]
Hi Enrico,
I would recommend creating the flexible catheter with small rigid body segments interconnected via joints (revolute with joint limits), and making the individual segments have simple collision shapes (check the collision tab in the ambf_addon and select any primitive for a singular collision shape). Regarding solving this problem via softbody approach; there are many limitations to our current implementation, it is really meant for simpler pick and place tasks at the moment and needs manual tuning to get reasonable results. We are working on improving the whole pipeline but that still might not be a good solution to this problem.

**Comment by Zimmo95** [comment]
Hi Adnan,
Thanks for the advice 
Enrico

**Comment by Zimmo95** [comment]
Hi Adnan, 
I created a probe with 60 links connected together and I succeeded to move it in ambf using the python client.
Now I am trying to move it inside an aorta (image) but, when I insert almost half of the probe inside the vessel, the probe starts to go very very slow. I also set the friction of aorta to 0 but the problem continues to exist.

![IMG_20210316_115028](https://user-images.githubusercontent.com/74068406/111298190-c542ea00-864e-11eb-8efd-852d14c225f5.jpg)
![IMG_20210316_114352](https://user-images.githubusercontent.com/74068406/111298198-c70cad80-864e-11eb-94fe-8c0eaefeda1a.jpg)


Thanks for your time
Enrico

**Comment by Zimmo95** [comment]
Hi Adnan, 
This is another problem, when the probe touch the inner surface of the aorta it disassembles 
![IMG_20210316_142132](https://user-images.githubusercontent.com/74068406/111317312-54a6c800-8664-11eb-8362-fb1a1d2a099b.jpg)

**Comment by adnanmunawar** [comment]
Hi Zimmo,
Unfortunately, usable collision detection using concave meshes (as the one you have) requires a fair bit of setup. Some of these steps include:
Trying to approximate the mesh via multiple collision primitives.
Making a lower resolution collision mesh by hand using it for the collision.
Having the concave mesh set as static (mass = 0), which may or may not be possible depending upon what you are trying to do.
Breaking down a mesh into smaller components, where each component is approximated by a convex hull.
All these things are supported in AMBF but the process of doing so is not documented. I shall have to create a tutorial in this regard.

**Comment by Zimmo95** [comment]
Hi Adnan, 
So, the problem is not the high number of meshes but their complexity?
Enrico

**Comment by Zimmo95** [comment]
Hi Adnan, 
I tried to go through a static little piece of pipe made up of 150 vertex with a mass of 0.001 kg and a collision convex hull but the problem still persists: the probe jumps out of the tube and starts vibrating and disassembling.
Do you have other suggestions?

Enrico
[
![Screenshot from 2021-03-22 15-07-02](https://user-images.githubusercontent.com/74068406/112003477-3ab42c00-8b21-11eb-8239-30d805b16eae.png)
](url)

**Comment by adnanmunawar** [comment]
Hi Zimmo, the version of ambf_addon that I see in the image does not allow the creation of convex hulls. Even though the field in the addon calls it a "CONVEX_HULL", it is still a concave mesh. The support for actual CONVEX_HULLs was added recently both in the ambf-1.0 (latest commit should already have the support) and the ambf_addon. We have not updated the ambf_addon submodule in the ambf-1.0 branch yet, you can get its latest version from its standalone repo: https://github.com/WPI-AIM/ambf_addon

That being said, just wanted to clarify a few points. A single convex hull is an enclosed surface that does not allow concavities and thus no holes or indents etc.  Also, keeping it as a concave mesh (or a CONVEX HULL as it says in this version of add-on), you can always visualize what the reduced mesh (the one to be saved for collision) looks like by clicking the button `Toggle Modifiers Visibility` in the ambf_addon main panel. This should give you an idea of what your collision mesh would look like. For optimum performance, a concave mesh such as the one that you have should be broken down into smaller components, where each can be approximated as a single convex mesh, then combined under a single collision shape. Again, this is a slightly involved process that needs to be documented.

Here are a few things that you can try with what you have so far. 
1) Reduce the number of elements of your caterer.
2) Visualize the low-resolution collision mesh of your tube to ensure it looks feasible, if it's too crazy, you can increase the `Collision Mesh Max Vertices` field and regenerate the mesh modifier until it starts looking acceptable. 
3) Run ambf in fixed time-stepping mode and with a lower physics frequency (let's say 60 Hz). Check this page to learn about the required CLIs https://github.com/WPI-AIM/ambf/wiki/Command-Line-Arguments.

**Comment by Zimmo95** [comment]
Hi Adnan, 
I downloaded the new version of ambf_addon and I created my convex hull but the collision shape is still a cube.

Thanks for your availability 
Enrico
![Screenshot from 2021-03-22 19-29-06](https://user-images.githubusercontent.com/74068406/112040110-136f5600-8b45-11eb-8aaf-1c0707366ac5.png)

**Comment by adnanmunawar** [comment]
You can ignore the yellow visual, it's only there for collision primitives.

**Comment by Zimmo95** [comment]
Thus, how can I check the collision convex hull?

**Comment by Zimmo95** [comment]
Hi Adnan, 
I splited every segment of the pipe (through their simmetry plans) in 2 half pipes and created CONVEX MESHES.
It seems to work, does it make sense in your opinion?
Enrico

**Comment by Zimmo95** [comment]
Hi Adnan,
I splited every segment of the pipe (through their simmetry plans) in 2 half pipes and created CONVEX MESHES.
It seems to work, does it make sense in your opinion?

If, on the other hand, I try to use a convex hull, the probe cannot enter the tube impacting against the entrance. Why?
Enrico

**Comment by adnanmunawar** [comment]
> Thus, how can I check the collision convex hull?`

For MESH-based collision, You can visualize the reduced mesh after clicking the button "Generate Low-Res Meshes" in the ambf_addon panel. The new low-res mesh would appear in place of your original mesh (thus your original mesh is not lost). Then you can enable/disable the view of this low res mesh by clicking the button "Toggle Modifiers Visibility" in the ambf_addon panel.

> If, on the other hand, I try to use a convex hull, the probe cannot enter the tube impacting against the entrance. Why?

This is because of how convex hulls are defined. I explained it a few comments earlier:

> That being said, just wanted to clarify a few points. A single convex hull is an enclosed surface that does not allow concavities and thus no holes or indents etc..

**Comment by Zimmo95** [comment]
Hi Adnan, 
I have studied a bit what are the convex hull and concave meshes.

summing up:
-If I divide my tube into segments that include a low number of vertices (ex: 150) using the button "Generate Low-Res Meshes" and then divide each segment into a convex upper and lower solid and finally generate concave meshes, I can penetrate the tube. The problem, however, is that the physics frequency drops dramatically to 1Hz. To overcome this problem you suggested me to divide each element into multiple collision primitive and use convex hulls.

My question is: is it necessary to split each STL into smaller STLs or is there a way to generate many convex hulls from a single stl?

Enrico

**Comment by adnanmunawar** [comment]
Hi Enrico,
Glad to know that. So the short answer is YES. We can have multiple objects (meshes) in Blender and we can save them as a single mesh, as an OBJ file (not STL). There are few extra steps involved though:

1) For mesh-based collision, AMBF uses the meshes that are saved in the `<path>/low_res` folder and uses the corresponding named meshes in the `<path>/high_res` folder.  You can replace the mesh in the `low_res` folder with whatever you desire and that mesh would be used to create a CONCAVE_MESH, CONVEX_HULL, or CONVEX_MESH depending on what you selected the `COLLISION SHAPE TYPE` in the ambf_addon.

``` yaml
bodies:
- BODY my_body
joints:
high resolution path: <path>/high_res/
low resolution path: <path>/low_res/
ignore inter-collision: true
namespace: /ambf/env/
BODY my_body:
  name: my_body
  mesh: my_body.OBJ
  collision mesh type: CONVEX_HULL
...
```

2) We can use Blender to generate extra meshes and select all the required meshes and then save them as a single OBJ file. Let's call each mesh as m_i where I = [1, 2, 3 ... N] that together form a single shape called S. Now due to some internal implementations of reading OBJ format, you HAVE to assign each m_i a separate material. After doing so, select all m_i's together (ONLY THOSE AND NOTHING ELSE), move the combined selection to the ORIGIN (OTHERWISE THE MESHES WILL HAVE A WEIRD OFFSET), and then export the SELECTION as an OBJ file.  Before saving, you HAVE to select certain options in the dialog box, these include `Enable: OBJ Objects`, `Forward: Y Forward`, and `Up: Z Up`. Now save it to the `low_res` folder replacing the original mesh or with a different filename. With this, AMBF will read this single OBJ file containing multiple meshes and create a separate convex hull for each m_i provided that `COLLISION MESH TYPE` was set to `CONVEX_HULL`. 

3) You can set the `MESH Type` as `OBJ` in the ambf_addon before saving the ADF file so that even the visual mesh is saved as an OBJ file. The rigid body data-block in the ADF file has a field called `mesh: <mesh_name>` which is combined with the `high_res` path to get the visual mesh and with `low_res` path to get the collision mesh. If you saved your collision mesh with a different name, you can manually add a field to the ADF file for the rigid body called `collision mesh: <different_mesh>`. The field `collision mesh` supersedes the `mesh` field for reading in the collision mesh. This would be useful if you want to rename your `collision` mesh to a different name so that it is not overwritten when you save ALL the meshes. Here is an example ADF file:

``` yaml
bodies:
- BODY my_body
joints:
high resolution path: <path>/high_res/
low resolution path: <path>/low_res/
ignore inter-collision: true
namespace: /ambf/env/
BODY my_body:
  name: my_body
  mesh: my_body.OBJ
  collision mesh: a_different_mesh.OBJ
  collision mesh type: CONVEX_HULL
...
```

As you can see, this is rather a cumbersome process. We are currently working on simplifying the pipeline and then we would add better documentation about this process.

Note: In step (2) generating meshes that represent your shape accurately while are still relatively simple is an involved process. There should be many different tools out there, some at least in Blender to automate the process a bit.

**Comment by adnanmunawar** [comment]
Glad to know that. So, in my opinion, you should be able to further increase the performance if you used Convex hulls but as I can see it is impractical if not impossible to generate them by hand for such a complicated geometry. I recently came across this tool, https://github.com/kmammou/v-hacd. I haven't had much time to test this out but it seems promising. What this might allow you to do is to automatically breakdown your mesh into convex hulls and then those could be saved as a single OBJ file similar to the process I described. If you ever get a chance to try this path out, I would be interested to know the results.

-Adnan

**Comment by Zimmo95** [comment]
Thanks for your suggestion.
It looks like a very useful and interesting add-on
I installed blender 2.80 and followed the installation instructions but unfortunately I ran into a similar problem with many other users: the add-on doesn't see the mesh (immage) and on the github this issue doesn't have an answer from the developer.
![Screenshot from 2021-03-25 22-38-52](https://user-images.githubusercontent.com/74068406/112547946-bf21db80-8dbb-11eb-8bda-05de2f6692b7.png)

Enrico

**Comment by adnanmunawar** [comment]
Ahh that is a bummer. Thanks for looking into this.

**Comment by adnanmunawar** [comment]
I had another suggestion for improving the speed of your collision detection. It seems that your mesh (aorta) is a dynamic body (with mass != 0). Collision detection with static concave meshes is much faster so if there is a good reason for your concave mesh to be moveable, you can still make it a static mesh (set its mass to 0) and use the ROS interface (the Python client) to change its pose, similar to how you control dynamic bodies. The only catch here would be that your static bodies do not collide with other static bodies but they do collide with dynamic bodies (thus your catheter collision would still work). Lastly, you can only control a static body's Pose. Setting its Velocity or Effort is currently not supported.

**Comment by Zimmo95** [comment]
The aorta is static, for this reason I succeeded to divide it in multiple stl without creating joints between them. 
Next week I will start to manage with the force feedback and maybe also with some simple soft bodies inside the aorta.

Thanks for your many suggestions!

**Comment by Zimmo95** [comment]
Hi Adnan, 
I'm trying to implement the force feedback on the tip of my probe.
I followed the "interaction forces" issue of Elisa and enabled the force feedback on the first joint of the probe but I cannot subscribe to the probe first link/state in order to display the interaction force.
How can i fix it?
Is possible to use a revolute joint or it's better to create a new fix joint and a small link on the tip of the probe?

Thank you for your availability 
Enrico

**Comment by adnanmunawar** [comment]
Hi Enrico,
Here are some answers to your queries:

>I followed the "interaction forces" issue of Elisa and enabled the force feedback on the first joint of the probe.

The links for which you want the force feedback should be connected to the joint with the `feedback` enabled. For example, if you want the force feedback for the distal (tip) link of a robot, a joint connected to that distal link is the one that you should be enabling the feedback for.

> I cannot subscribe to the probe first link/state in order to display the interaction force

Can you describe this in detail. Is the ROS topic for the link not being published? Is the link set as passive?

> Is possible to use a revolute joint or it's better to create a new fix joint and a small link on the tip of the probe?

You can use any type of joint to enable reporting of the force feedback on the bodies connected to it, however, a fixed joint should be the most ideal for this purpose.

**Comment by Zimmo95** [comment]
Hi Adnan, 
I enabled the joint (revolute) of the tip (picture) but I cannot feel the force feedback.
[Adnan:Can you describe this in detail. Is the ROS topic for the link not being published? Is the link set as passive?]
The link is published correctly, I wrongly supposed that I have to publish something on the Link topic in order to feel the feedback. 
Do you think that I have to create an extra joint (fixed one) on the tip and connect the tip with a very small object (like a sphere)?

Enrico
![Screenshot from 2021-04-08 16-28-59](https://user-images.githubusercontent.com/74068406/114045486-5856f480-9888-11eb-91fa-380b253d0a75.png)

**Comment by Zimmo95** [comment]
Hi Adnan,
I enabled the joint (revolute) of the tip (picture) but I cannot feel the force feedback.
[Adnan:Can you describe this in detail. Is the ROS topic for the link not being published? Is the link set as passive?]
The link is published correctly, I wrongly supposed that I have to publish something on the Link topic in order to feel the feedback.
Do you think that I have to create an extra joint (fixed one) on the tip and connect the tip with a very small object (like a sphere)?

Enrico
![Screenshot from 2021-04-08 16-41-03](https://user-images.githubusercontent.com/74068406/114046584-4033a500-9889-11eb-8733-7a3d52cffdca.png)

**Comment by Zimmo95** [comment]
Hi Adnan,
I followed the istructions of "interaction force" issue.
I enabled the force feedback on the tip and created a collision shape

Enrico


![Screenshot from 2021-04-09 12-24-21](https://user-images.githubusercontent.com/74068406/114167462-411f1200-992f-11eb-862a-df8912d1cd21.png)
![Screenshot from 2021-04-09 12-23-43](https://user-images.githubusercontent.com/74068406/114167471-42503f00-992f-11eb-9cfb-9e685538ac06.png)

**Comment by adnanmunawar** [comment]
Hi Enrico, thanks for the update. Is your issue resolved after this:

> I followed the istructions of "interaction force" issue.
I enabled the force feedback on the tip and created a collision shape

**Comment by Zimmo95** [comment]
Hi Adnan, 
yes, thanks for asking!
I followed those instructions and I published on the correct topic the force feedback in the python Client.

Enrico
![Screenshot from 2021-04-13 10-29-43](https://user-images.githubusercontent.com/74068406/114521979-32906d80-9c43-11eb-8c31-05aaf6cc39c7.png)

**Comment by emakr49** [comment]
Hi @Zimmo95 ,
I'm trying to do something similar to what you're doing. But it seems my catheter model doesn't work. Can you share your model, please?
Many thanks!

**Comment by Zimmo95** [comment]
Hi @emakr49,
In order to model a catheter, you have to create a couple of links and connect them with a joint using the ambf add-on in Blender.
This is an example of what you have to do.
[Catheter.zip](https://github.com/WPI-AIM/ambf/files/6507044/Catheter.zip)
Load it on blender using the ambf add-on and edit it to your liking.

Best, 
Enrico
