### ISSUE TITLE
Simulation of plants

### ISSUE THREAD

**Issue by karla-brueck** [WPI-AIM/ambf#123]
Hi Adnan, 

I want to simulate a plant in ambf. The leaves should be flexible and the stems also to a certain extent. Is that possible in AMBF? If so, which branch is best for this and how do you get started? 

Thanks for your availability,

Karla

**Comment by adnanmunawar** [comment]
Hi Karla,
This seems like an interesting application, one which we have not thought of before. What is currently possible in AMBF is the generation of the scene objects via AMBF Description Format (ADF) which a description format written in YAML. Using this format, one can spawn unique Soft Bodies that are not interconnected to each other or to other Rigid Bodies. Additionally, a "flexible body", if modeled as a Soft Body, would have uniform structural properties (stiffness etc.) throughout. This is probably not what you have in mind as you desire variable local structural properties. 

You could theoretically make it work by making some parts structurally redundant, i.e in your mesh, have faces/edges that create a redundant structure at stiffer parts and then sparser interconnection at flexible parts. Generally, soft body simulation is finicky and requires a considerable amount of manual tuning. Depending upon how comfortable you are with C++ programming, you could dive into AMBF source code and then control the local softbody structural properties directly which are currently not possible via the ADF.

In any case, I would suggest using the `restructure` branch.
