### ISSUE TITLE
transparent object

### ISSUE THREAD

**Issue by Zimmo95** [WPI-AIM/ambf#129]
Hi Adnan, 
Is it possible to create and import a transparent object?

Enrico

**Comment by adnanmunawar** [comment]
Hi Enrico, Yes, you can set the transparency value in the ADF for the object or use the material tab in the ambf_addon. This is a video of how to do that. Note, when you enable the material, make sure to click "use nodes" to toggle the node-based rendering (in Blender) to off. Then you can set the color/transparency using the color wheel. Now when you save the ADF, the data should be consistent in ADF.

![transparency](https://user-images.githubusercontent.com/5005445/114429331-44aed500-9b8b-11eb-90f8-bd478324f5ef.gif)

**Comment by Zimmo95** [comment]
Hi Adnan, 
It works perfectly.
Thanks for your help

Enrico
