### ISSUE TITLE
FILE.PNG

### ISSUE THREAD

**Issue by Zimmo95** [WPI-AIM/ambf#134]
Hi Adnan, 
I would like to know how to create a floor with a particular texture using a picture.png
I tried to insert in the high resolution folder a floor.png file (as the checkered floor) but nothing happened.

Best, 
Enrico

**Comment by adnanmunawar** [comment]
You can assign a texture to a mesh (object) in Blender and then save the meshes as `.OBJ` format using the `ambf_addon`.  There should be plenty of tutorials online to show you how to apply texture to an object using Blender.

The `ambf_addon` gives you an option to save the meshes in multiple different formats with `.STL` being the default option. Just change the format to `.OBJ` and the addon will then save the meshes and the textures for all objects that have them defined. Don't forget to save the ADF file as well to update the meshes information.

**Comment by Zimmo95** [comment]
It works. 
Thank you very much
