### ISSUE TITLE
Issue with depth point cloud coordinates

### ISSUE THREAD

**Issue by adnanmunawar** [WPI-AIM/ambf#139]
The equations need some correction.

**Comment by nag92** [comment]
what is wrong with the point cloud?

**Comment by adnanmunawar** [comment]
The max-width and max-height calculation were wrong (swapped):

This is what it was before

```cpp
maxX = 2.0 * cAbs(f) * cTanRad(fva/2.0);
maxY = maxX / ar;
```
f is Far Plane, and fva is the Field View Angle.

The fva measures the vertical frustum angle but the above equation was considering it as a horizontal frustum angle.

These should be correct equations as added via the commit. 
```cpp
maxY = 2.0 * cAbs(f) * cTanRad(fva/2.0);
maxX = maxY * ar;
```
