### ISSUE TITLE
List of prerequsite

### ISSUE THREAD

**Issue by cshreyastech** [WPI-AIM/ambf#14]
It would be helpful to have a list of prerequisites like ubuntu versions, packages and hardware configurations to use this project

Thanks

**Comment by adnanmunawar** [comment]
I agree, having a list of prerequisites and tested platforms would be super useful. I shall start populating the list, so far I have tested on Ubuntu 16, 17 and 18 and Mac OS Mojave. Although the ROS modules aren't built in Mac.
