### ISSUE TITLE
Error on running the simulator

### ISSUE THREAD

**Issue by Irennnne** [WPI-AIM/ambf#176]
Hello,
I am new on both ROS and AMBF. I found these errors when I tried to run the simulator. 
Could you give me some advice? 
Thank you.

Best,
Irene
![error](https://user-images.githubusercontent.com/99130111/168553346-0e9113cc-cd14-4f65-98f1-6edecd0cabc9.png)

**Comment by adnanmunawar** [comment]
Hello Irene,

Thanks for pointing this out. These specific 'errors' are expected behavior and should not affect the simulation. We may remove the printing of these in the future as they were meant for internal debugging.

-Adnan

**Comment by Irennnne** [comment]
> 
Thank you !!
