### ISSUE TITLE
namespace arg in simulator executable does not appear to be working

### ISSUE THREAD

**Issue by htp2** [WPI-AIM/ambf#178]
I was hoping to run multiple simulations simultaneously, but cannot start two as it creates two ros nodes of the same name (/ambf_comm_node). I noticed this was addressed in #54 by adding a --ns arg to the ambf_simulator executable.

However, when I try this, I don't see any change.

<Terminal 1>
```
./ambf_simulator --ns /test/
```
<Terminal 2>
```
rosnode list

/ambf_comm_node
/rosout
```

Curious if this feature was removed, or if there is a better way to run multiple simulations at the same time. Thanks!

I should note, in the short-term, I'm just using the workaround suggested in #54 and running multiple roscore

**Comment by adnanmunawar** [comment]
Thanks for pointing this out Henry. This must have broken quite a while back, I shall fix it soon.

**Comment by adnanmunawar** [comment]
Hi Henry, can you please try PR #180 to see if it resolves the issue.

**Comment by htp2** [comment]
Hi Adnan - got a chance to test this today. Works great, thanks!

**Comment by adnanmunawar** [comment]
Fixed in the above PR
