### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by VigneshManoj** [WPI-AIM/ambf#2]
The following error occured while building the ambf simulator from git repository:

/usr/bin/ld: ../libambf_framework.a(CBulletGenericObject.cpp.o): undefined reference to symbol '_ZNK3ros9Publisher7publishERKN5boost8functionIFNS_17SerializedMessageEvEEERS3_'
//opt/ros/melodic/lib/libroscpp.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ambf_simulator/CMakeFiles/ambf_simulator.dir/build.make:135: recipe for target '../bin/lin-x86_64/ambf_simulator' failed
make[2]: *** [../bin/lin-x86_64/ambf_simulator] Error 1
CMakeFiles/Makefile2:1163: recipe for target 'ambf_simulator/CMakeFiles/ambf_simulator.dir/all' failed
make[1]: *** [ambf_simulator/CMakeFiles/ambf_simulator.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by adnanmunawar** [comment]
This issue arises from placing the ambf_ros_modules in the ROS workspace and is not directly related to AMBF.
