### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by vidurvij** [WPI-AIM/ambf#4]
When loaded without a robot being uncommented this pops up and when the process is interrupted by Ctrl + C the simulator pops up without a robot where i can interact with the surroundings.

When a robot model is uncommented from the launch.yaml file, the message presists and simulator does not pop up when Ctrl + C is pressed.

[ERROR] [1554766455.928841748]: [registerPublisher] Failed to contact master at [localhost:11311].  Retrying...

**Comment by adnanmunawar** [comment]
You have to run roscore if you want to control via ROS. This is what the simulator is notifying you. If you type Ctrl-C at simulator launch it kills the ros-plugin and hence goes on without trying to establish ros-communication. This is perfectly fine unless you want to control simulation objects using ROS topics.
