### ISSUE TITLE
[Discussion] Topic definition and namespace handling for multiple robots for controller design

### ISSUE THREAD

**Issue by DhruvKoolRajamani** [WPI-AIM/ambf#41]
Currently, spawning multiple instances of the same model appends a number to the link like this:  

![image](https://user-images.githubusercontent.com/35770744/70379342-6fcf4780-18f9-11ea-8be9-31720376124a.png)

My suggestion is to append the number to the namespace:

![image](https://user-images.githubusercontent.com/35770744/70379379-d2c0de80-18f9-11ea-974e-3a15a0064b61.png)

And also have a feature of maybe storing the namespaces in a list on the param server if ros is running OR publish a topic with the namespace prefixes.

![image](https://user-images.githubusercontent.com/35770744/70379392-10256c00-18fa-11ea-9ae3-352c6d37139d.png)

The need for this is for designing a controller, modifying the prefix as compared to the link names might be cleaner when describing the details of a robot in one or many environments.

**Comment by adnanmunawar** [comment]
Thanks for creating this Dhruv. As per our discussion earlier, the design that I had in mind was to use a logic similar to directory management. Therefore a newly added object with a colliding name is resolved by appending an index with it's name. One could argue that a namespace modification, as is employed by Gazebo, is another viable solution. And I agree.

So essentially, this boils down to how you view the simulation and the associated objects. In Blender such naming collision is handled by renaming with an index, somewhat similar to AMBF although not identical. So AMBF is not alone is taking this approach.  

That being said, I do think we should have an implementation wherein we provide a flag that allows users to chose what kind of naming resolution they prefer. However, at the moment, there are a few other important updates that I need to attend to before I delve into that.

**Comment by DhruvKoolRajamani** [comment]
Thanks for the clarification! I definitely agree with your logic, ambf is a platform which leverages Blender for meshes and it would make sense to propagate a similar naming convention. The feature to allow users to switch between different conventions seems neat as well and I'll be happy to assist you as and when the issue comes along your agenda.
