### ISSUE TITLE
Purpose of the joint message in object command

### ISSUE THREAD

**Issue by vidurvij** [WPI-AIM/ambf#5]
[https://github.com/WPI-AIM/ambf/blob/master/ambf_ros_modules/ambf_msgs/msg/ObjectCmd.msg](url)

**Comment by adnanmunawar** [comment]
We are working on the documentation. Here is a start : 

https://github.com/WPI-AIM/ambf/wiki/Control-AMBF-Simulator-Using-ROS-Messages

**Comment by adnanmunawar** [comment]
A added a basic example written in python that leverages the messages the Python client. Here is the link to the example

https://github.com/WPI-AIM/ambf/wiki/A-Basic-Example

**Comment by vidurvij** [comment]
Hi Adnan,
I have been trying to access the articles above but it says I dont have the
permission to edit the wiki. And it redirects me to ambf wiki landing page.
Thanks
Vidur

**Comment by adnanmunawar** [comment]
Sorry about that. Have been restructuring the wiki a bit so the old link became deprecated. Here is the new link. 
https://github.com/WPI-AIM/ambf/wiki/Understanding-ROS-Message-Payloads

And then to get a hands-on example. Please look at these two:

https://github.com/WPI-AIM/ambf/wiki/Controlling-dVRK-Manipulators

https://github.com/WPI-AIM/ambf/wiki/Controlling-a-Toy-Car

**Comment by vidurvij** [comment]
How do we install the module ambf_client used in the example code ?

**Comment by adnanmunawar** [comment]
@vidurvij I moved this to a new issue
