### ISSUE TITLE
[Release] Spawning multiple instances of clients for remote sessions

### ISSUE THREAD

**Issue by DhruvKoolRajamani** [WPI-AIM/ambf#54]
Refer to the [thread](https://answers.ros.org/question/193062/how-to-run-multiple-independent-gazebo-instances-on-the-same-machine/) to setup multiple rosmasters.

- [x] Modify current namespace schema `/ambf/env/` to `/ambf/user_envNo/env/` 
- [x] Allow -p port to be specified for ambf client instances.

**Comment by adnanmunawar** [comment]
I tested running multiple `roscore`s on the same machine and multiple instances of AMBF and they work as expected.

Usage 

```
Terminal 1
roscore -p <first_port_num>

Terminal 2
export ROS_MASTER_URI=http://localhost:<first_port_number>
./ambf_simulator <any necessary CLIs>

Terminal 3
roscore -p <second_port_num>

Terminal 4
export ROS_MASTER_URI=http://localhost:<second_port_number>
./ambf_simulator <any necessary CLIs>

and so on ...
```

**NOTE:** Make sure to `export` the correct `ROS_MASTER_URI`'s on all the terminals running the Python AMBF client to connect to the proper `roscore` and AMBF instance.

**Comment by adnanmunawar** [comment]
This commit f9db7770404e56810c7caff84c33c6917284dac9 allows a user to run ambf with the CLI arg `--ns` and specify a forced prefix to the namespace. 
**Usage:**
```
./ambf_simulator <desired_adf_files> --ns /test/
```
This will result in the string `"/test/"` to be appended to all the topics regardless of whether or not they  are specified in the relevant ADF files with an absolute namespace (e.g. `"/ambf/env/"`).

**Comment by DhruvKoolRajamani** [comment]
Can we close this?
