### ISSUE TITLE
Ability to create point cloud for the robot

### ISSUE THREAD

**Issue by FaridTavakol** [WPI-AIM/ambf#68]
Potential uses for this feature: the ability to visualize the workspace of the robot, trace and visualize the end effector's path in the simulation is real-time

**Comment by adnanmunawar** [comment]
This feature was added in feat-communication branch at this commit 66a707df97c9ef2e8fc00e97fcb916c41ac98c50. Should be merged into the master branch soon.

**Comment by adnanmunawar** [comment]
Feature added in ambf-1.0
