### ISSUE TITLE
use both vel and velocity(ies)

### ISSUE THREAD

**Issue by nag92** [WPI-AIM/ambf#76]
In rigid body class half the functions use "vel" and the other half use "velocity". Should this be consistent? It would make it easier to have the same names style through out.

**Comment by adnanmunawar** [comment]
Thanks for creating this issue. That is a good catch. I was creating some documentation the other day and noticed the inconsistency as well. Would fix it before merging back into master.

**Comment by nag92** [comment]
which do you want? I can quickly resolve all the inconsistency.

**Comment by adnanmunawar** [comment]
Thanks for taking this up. I suppose that since we are using “pos” instead of “position”, we should “vel” instead of “velocity”. There are some code examples in ambf_ros_modules that might need to be updated as well.

**Comment by adnanmunawar** [comment]
Fixed in the feat-communication branch at 8b018738dc30e304e8bb02b3ae941d97da4e53da
