### ISSUE TITLE
Set Text Color in AMBF Simulator Window

### ISSUE THREAD

**Issue by nag92** [WPI-AIM/ambf#86]
Would it be possible to change the text color in the sim to red or something? it is hard to read has black text with the black and white floor.

**Comment by adnanmunawar** [comment]
We can add some functionality to the world file where one may specify the text color. Meanwhile you can change the color to your liking in your local branch right here.

https://github.com/WPI-AIM/ambf/blob/ambf-1.0/ambf_framework/afFramework.cpp#L6467

**Comment by nag92** [comment]
awsome thank you
