### ISSUE TITLE
Command-line specification of multiple ADF files fails if a space is present between two files.

### ISSUE THREAD

**Issue by nag92** [WPI-AIM/ambf#93]
I dont know if this is a bug or feature but if there is a space after the comma, it fails to launch 

this works 
```bash
./ambf_simulator -a file.yaml,file2.yaml

```

this does not work 
```bash
./ambf_simulator -a file.yaml, file2.yaml

```

**Comment by adnanmunawar** [comment]
This is not ideal but stems from the way command-line arguments are handled. An empty space ' ' automatically means a new argument and thus results in the behavior that you defined.
